### ISSUE TITLE
Add more docs

### ISSUE THREAD

**Issue by mrclay** [aspen-institute/pantheon-archive-action#2]
Document need for the checkout step before usage:

```
      - uses: actions/checkout@v4
        with:
          permissions:
            contents: write
```

"Go to your repository setting Actions -> General, then make sure Actions permissions is set to Allow, and make sure Workflow permissions is set to Read and write permissions"

I'm not sure if this is also needed for the `pantheon-archive-action` step:

```
          permissions:
            contents: write
```
